esercizio4: esercizio4.o random.o random.h
	g++ esercizio4.o random.o -o esercizio4
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio4.o: es4.cpp random.h
	g++ -c es4.cpp -o esercizio4.o