esercizio7_2: esercizio7_2.o random.o random.h Monte_Carlo_NVT.h
	g++ random.o esercizio7_2.o -o esercizio7_2
esercizio7_2.o: es7_2.cpp Monte_Carlo_NVT.h
	g++ -c es7_2.cpp -o esercizio7_2.o
random.o : random.cpp random.h
	g++ -c random.cpp -o random.o