esercizio1_3: esercizio1_3.o random.o random.h functions.h
	g++ esercizio1_3.o random.o -o esercizio1_3
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio1_3.o: es1_3.cpp random.h functions.h
	g++ -c es1_3.cpp -o esercizio1_3.o