esercizio6: esercizio6.o random.o random.h Monte_Carlo_ISING_1D.h
	g++ random.o esercizio6.o -o esercizio6
esercizio6.o: es6.cpp Monte_Carlo_ISING_1D.h
	g++ -c es6.cpp -o esercizio6.o
random.o : random.cpp random.h
	g++ -c random.cpp -o random.o