esercizio1_1: esercizio1_1.o random.o random.h functions.h
	g++ esercizio1_1.o random.o -o esercizio1_1
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio1_1.o: es1_1.cpp random.h functions.h
	g++ -c es1_1.cpp -o esercizio1_1.o