esercizio7_1: esercizio7_1.o random.o random.h Monte_Carlo_NVT.h
	g++ random.o esercizio7_1.o -o esercizio7_1
esercizio7_1.o: es7_1.cpp Monte_Carlo_NVT.h
	g++ -c es7_1.cpp -o esercizio7_1.o
random.o : random.cpp random.h
	g++ -c random.cpp -o random.o