esercizio1_2: esercizio1_2.o random.o random.h
	g++ esercizio1_2.o random.o -o esercizio1_2
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio1_2.o: es1_2.cpp random.h
	g++ -c es1_2.cpp -o esercizio1_2.o