esercizio2_2: esercizio2_2.o random.o random.h functions.h
	g++ esercizio2_2.o random.o -o esercizio2_2
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio2_2.o: es2_2.cpp random.h functions.h
	g++ -c es2_2.cpp -o esercizio2_2.o