esercizio3_1: esercizio3_1.o random.o random.h functions.h
	g++ esercizio3_1.o random.o -o esercizio3_1
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio3_1.o: es3_1.cpp random.h functions.h
	g++ -c es3_1.cpp -o esercizio3_1.o