esercizio2_1: esercizio2_1.o random.o random.h functions.h
	g++ esercizio2_1.o random.o -o esercizio2_1
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio2_1.o: es2_1.cpp random.h functions.h
	g++ -c es2_1.cpp -o esercizio2_1.o