esercizio5_1: esercizio5_1.o random.o random.h functions.h
	g++ esercizio5_1.o random.o -o esercizio5_1
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio5_1.o: es5_1.cpp random.h functions.h
	g++ -c es5_1.cpp -o esercizio5_1.o