esercizio8_1: esercizio8_1.o random.o random.h
	g++ esercizio8_1.o random.o -o esercizio8_1
random.o: random.cpp random.h
	g++ -c random.cpp -o random.o
esercizio8_1.o: es8_1.cpp random.h
	g++ -c es8_1.cpp -o esercizio8_1.o